config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects, except: :show do
    resources :tasks, except: :show
  end
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :delete_all

  validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :description, :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable, authentication_keys: [:nickname]

  has_many :projects

  validates :first_name, :last_name, :nickname, presence: true
  validates :nickname, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :devise_parameter_sanitizer, if: :devise_controller?

  protected

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[edit update destroy]

  def index
    @projects = current_user.projects.order(id: :desc)
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      flash[:success] = 'Projeto cadastrado com sucesso.'
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      flash[:success] = 'Projeto atualizado com sucesso.'
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    flash[:success] = 'Projeto excluído com sucesso.' if @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title)
  end

  def set_project
    @project = current_user.projects.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[edit update destroy]

  def index
    @tasks = @project.tasks.order(id: :desc)
  end

  def new
    @task = @project.tasks.build
  end

  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      flash[:success] = 'Tarefa cadastrada com sucesso.'
      redirect_to project_tasks_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      flash[:success] = 'Tarefa atualizada com sucesso.'
      redirect_to project_tasks_path
    else
      render :edit
    end
  end

  def destroy
    flash[:success] = 'Tarefa excluída com sucesso.' if @task.destroy
    redirect_to project_tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:description, :status)
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def set_project
    @project = current_user.projects.find(params[:project_id])
  end
end

app/controllers/user/parameter_sanitizer.rb
class User::ParameterSanitizer < Devise::ParameterSanitizer
  def initialize(*)
    super
    keys = %i[first_name last_name nickname email password password_confirmation]
    permit(:sign_up, keys: keys)
    permit(:account_update, keys: keys)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message_class(level)
    case level.to_s
    when 'notice'
      'is-success'
    when 'success'
      'is-success'
    when 'info'
      'is-info'
    when 'error'
      'is-danger'
    when 'alert'
      'is-danger'
    when 'danger'
      'is-danger'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :page_title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/shared/header' %>
    <section class="section">
      <%= yield %>
    </section>
    <%= render partial: 'layouts/shared/footer' %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="footer has-background-dark has-text-white-ter">
  <div class="content has-text-centered">
    <p>
      &copy; <%= Date.today.year %> ProjectManager  - Todos os direitos reservados <br>
      Desenvolvido por <strong class="has-text-danger">Hendrew Hélio</strong>
    </p>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<nav class="navbar is-danger" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, alt: 'project manager', class: 'navbar-item' do %>
      <h1 class="title logo has-text-white-ter has-text-weight-normal">Project<span class="has-text-weight-medium">Manager</span></h1>
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <% if user_signed_in? %>
    <div class="navbar-start">
      <%= link_to 'Projetos', projects_path, alt: 'projetos', class: 'navbar-item' %>
    </div>
    <div class="navbar-end">
      <%= link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_registration_path, alt: 'editar perfil', class: 'navbar-item' %>
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to 'Sair', destroy_user_session_path, alt: 'sair', class: 'button is-light', method: :delete %>
        </div>
      </div>
    </div>
    <% else %>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to new_user_registration_path, alt: 'registrar-se', class: 'button is-primary' do %>
          <strong>Registrar-se</strong>
          <% end %>
          <%= link_to new_user_session_path, alt: 'entrar', class: 'button is-light' do %>
          <strong>Entrar</strong>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</nav>

app/views/projects/_form.html.erb
<% content_for :page_title, "#{page} Projeto" %>

<div class="container">
  <div class="columns">
    <div class="column is-5">
      <h2 class="title is-2 has-text-weight-light"><%= page %> Projeto</h2>
    </div>
    <div class="column is-7 has-text-right">
      <%= link_to 'Voltar', projects_path, alt: 'voltar', class: 'button is-light' %>
    </div>
  </div>
  <hr>
  <br>

  <%= render partial: 'shared/flash' %>

  <% if @project.errors.any? %>
  <div class="notification is-danger">
    <h3 class="title is-4">
      <%= pluralize(@project.errors.count, 'erro', 'erros') %>
      <%= @project.errors.count > 1 ? 'proibiram' : 'proibiu' %> este projeto de ser salvo:
    </h3>

    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="box">
    <%= form_with model: [@project], local: true do |f| %>
      <div class="field">
        <%= f.label :title, class: 'label' %>
        <div class="control">
          <%= f.text_field :title, autofocus: true, autocomplete: 'title', class: 'input' %>
        </div>
      </div>

      <br>

      <%= f.submit nil, class: 'button is-primary' %>
      <%= button_tag 'Resetar', type: :reset, class: 'button is-light' %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'form', page: 'Editar' %>

app/views/projects/index.html.erb
<% content_for :page_title, "Projetos" %>

<div class="container">
  <div class="columns">
    <div class="column is-3">
      <h2 class="title is-2 has-text-weight-light">Projetos</h2>
    </div>

    <div class="column is-9 has-text-right">
      <%= link_to 'Novo', new_project_path, alt: 'novo', class: 'button is-primary' %>
    </div>
  </div>

  <hr>
  <br>

  <%= render partial: 'shared/flash' %>

  <div class="table-responsive">
    <table class="table is-bordered is-fullwidth table-vertical-align-center">
      <thead>
        <tr>
          <th>#</th> <th>Título</th> <th>Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
        <tr>
          <td><%= project.id %></td>
          <td><%= project.title %></td>
          <td>
            <%= link_to 'Tarefas', project_tasks_path(project), alt: 'tarefas', class: 'button is-info', title: 'Tarefas' %>
            <%= link_to 'Editar', edit_project_path(project), alt: 'editar', class: 'button is-warning', title: 'Editar' %>

            <%= link_to 'Excluir', project_path(project), method: :delete, data: { confirm: 'Você tem certeza?' }, alt: 'excluir', class: 'button is-danger', title: 'Excluir' %>
          </td>
        </tr>
        <% end %>

        <% if @projects.length == 0 %>
        <tr>
          <td colspan="3">Nenhum projeto encontrado.</td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form', page: 'Novo' %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="notification <%= flash_message_class(key) %>">
    <button class="delete" onclick="this.parentElement.style.display = 'none'"></button>
    <%= value %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<% content_for :page_title, "#{page} Tarefa" %>

<div class="container">
  <div class="columns">
    <div class="column is-5">
      <h2 class="title is-2 has-text-weight-light"><%= page %> Tarefa</h2>
      <h4 class="title is-4 has-text-grey-light"><%= @project.title %></h4>
    </div>
    <div class="column is-7 has-text-right">
      <%= link_to 'Voltar', project_tasks_path(@project), alt: 'voltar', class: 'button is-light' %>
    </div>
  </div>
  <hr>
  <br>

  <%= render partial: 'shared/flash' %>

  <% if @task.errors.any? %>
  <div class="notification is-danger">
    <h3 class="title is-4">
      <%= pluralize(@task.errors.count, 'erro', 'erros') %>
      <%= @task.errors.count > 1 ? 'proibiram' : 'proibiu' %> esta tarefa de ser salva:
    </h3>

    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="box">
    <%= form_with model: [@project, @task], local: true do |f| %>
      <div class="field">
        <%= f.label :description, class: 'label' %>
        <div class="control">
          <%= f.text_field :description, autofocus: true, autocomplete: 'description', class: 'input' %>
        </div>
      </div>

      <div class="field">
        <%= f.label :status, class: 'label' %>
        <div class="control">
          <div class="select">
            <%= f.select(:status, [['Não Iniciado', 1], ['Iniciado', 2], ['Finalizado', 3]]) %>
          </div>
        </div>
      </div>

      <br>

      <%= f.submit nil, class: 'button is-primary' %>
      <%= button_tag 'Resetar', type: :reset, class: 'button is-light' %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', page: 'Editar' %>

app/views/tasks/index.html.erb
<% content_for :page_title, "Tarefas" %>

<div class="container">
  <div class="columns">
    <div class="column is-9">
      <h2 class="title is-2 has-text-weight-light"><%= @project.title %></h2>
      <h2 class="title is-4 has-text-grey-light">Tarefas</h2>
    </div>

    <div class="column is-3 has-text-right">
      <%= link_to 'Voltar', projects_path, alt: 'voltar', class: 'button is-light' %>
      <%= link_to 'Nova', new_project_task_path, alt: 'nova', class: 'button is-primary' %>
    </div>
  </div>

  <hr>
  <br>

  <%= render partial: 'shared/flash' %>

  <div class="table-responsive">
    <table class="table is-bordered is-fullwidth table-vertical-align-center">
      <thead>
        <tr>
          <th>#</th> <th>Descrição</th> <th>Status</th> <th>Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
        <tr>
          <td><%= task.id %></td>
          <td><%= task.description %></td>

          <td>
          <% if task.status == 1 %>
            <span class="has-background-danger has-text-white">Não iniciado</span>
          <% elsif task.status == 2 %>
            <span class="has-background-warning">Iniciado</span>
          <% elsif task.status == 3 %>
            <span class="has-background-success has-text-white">Finalizado</span>
          <% end %>
          </td>

          <td>
            <%= link_to 'Editar', edit_project_task_path(@project, task), alt: 'editar', class: 'button is-warning', title: 'Editar' %>
            <%= link_to 'Excluir', project_task_path(@project, task), method: :delete, data: { confirm: 'Você tem certeza?' }, alt: 'excluir', class: 'button is-danger', title: 'Excluir' %>
          </td>
        </tr>
        <% end %>

        <% if @tasks.length == 0 %>
        <tr>
          <td colspan="4">Nenhuma tarefa encontrada.</td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render 'form', page: 'Nova' %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="notification is-danger">
    <h2 class="title is-3">
      <%= I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Registrar-se", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>